### ISSUE TITLE
embed pdf error

### ISSUE THREAD

**Issue by colorzhang** [ray-project/langchain-ray#11]
(ReadBinary->FlatMap->FlatMap pid=17023, ip=172.31.69.122) OSError: When reading information for key '2205.13708v1.HiJoNLP_at_SemEval_2022_Task_2_Detecting_Idiomaticity_of_Multiword_Expressions_using_Multilingual_Pretrained_Language_Models.pdf' in bucket 'ray-llm-batch-inference': AWS Error [code 15]: No response body. [repeated 157x across cluster]
(ReadBinary->FlatMap->FlatMap pid=27798, ip=172.31.75.31) invalid pdf header: b'<?xml'
(ReadBinary->FlatMap->FlatMap pid=27798, ip=172.31.75.31) EOF marker not found

**Comment by kamil-kaczmarek** [comment]
HI @colorzhang looks like you have invalid pdf file.

**Comment by colorzhang** [comment]
Thanks, solved by downloading pdfs to my bucket.
